### ISSUE TITLE
Lab 5 Skytap environment - Password for Ansible login not working

### ISSUE THREAD

**Issue by hsternkicker** [ibm-garage-tsa/cp4mcm-demohub#2]
Tried to do lab 5 and especially the part with the Ansible configuration, but the admin password does not work. Tried it with the saved password from the browser and with the one that is in the stored credentials of the Skytap environment.

**Comment by dymaczew** [comment]
Thanks for the info. I have fixed the Skytap template with the right credentials, but until it is propagated I have added the right credentials to the tutorial as well.
